version: 2.1

setup: true  # uses continuation-orb, generated pipelines

# =================== global config

orbs:
  continuation: circleci/continuation@0.4.0
  #checkov:skip=CKV_CIRCLECIPIPELINES_3
  terraform: twdps/terraform@dev:latest
  op: twdps/onepassword@1.0.0
  do: twdps/pipeline-events@2.0.0

globals:
  - &context empc-lab
  - &executor-image twdps/circleci-infra-aws:alpine-4.15.0
  - &snyk-organization twdps

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

# ===================================

commands:

  set-environment:
    description: set environment variables or create credential files from templates
    parameters:
      static:
        description: set-environment for static-analysis-only run
        type: boolean
        default: false
      env-credentials:
        description: identifier for op.*.env file
        type: string
      instance-name:
        description: cluster role instance and tf workspace name
        type: string
        default: ""
      release-pipeline-name:
        description: name of the release pipeline to generate from multi-regional release, global json file (not needed for static=true)
        type: string
        default: ""
    steps:
      - op/env:
          env-file: op.<< parameters.env-credentials >>.env
      - run:
          name: set ~/.terraformrc
          command: op inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - unless:
          condition: << parameters.static >>
          steps:
            - restore_cache:
                name: restore circlecigen generated tfvars
                keys:
                  - circlecigen-tfvars-{{ .Revision }}-<< parameters.release-pipeline-name >>
            - run:
                name: set << parameters.instance-name >> role instance environment settings (tfvars)
                command: op inject -i environments/<< parameters.instance-name >>.tfvars.json -o << parameters.instance-name >>.auto.tfvars.json

  run-inspec-tests:
    description: run inspec aws configuration tests
    parameters:
      instance-name:
        description: tf workspace name
        type: string
    steps:
      - run:
          name: run inspec tests
          environment:
            WORKSPACE: <<parameters.instance-name>>
          command: bash scripts/run_inspec_integration_tests.sh << parameters.instance-name >>

jobs:

  launch-dynamic-pipeline:
    parameters:
      release-pipeline-name:
        description: name of the release pipeline generated from multi-regional release
        type: string
      custom-template-file:
        description: Custom CircleCI template file to use for pipeline generation
        type: string
        default: ""
    executor: continuation/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install needed packages
          command: |
            sudo apt-get update && sudo apt-get install python3-pip && pip install circlecigen==0.0.9
            curl -L https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0-beta.01/op_linux_amd64_v2.18.0-beta.01.zip -o op.zip
            unzip -o op.zip && sudo mv op /usr/local/bin/op
      - run:
          name: generate continuation pipeline
          command: |
            op read op://empc-lab/psk-platform-global-env-values/control-plane-deployment | base64 -d > environments/multi.json
            circlecigen << parameters.release-pipeline-name >> \
                        --workflow << parameters.release-pipeline-name >>-deployment \
                        <<#parameters.custom-template-file>>--template << parameters.custom-template-file >><</parameters.custom-template-file>>
      - save_cache:
          name: persist circlecigen generated files between workflows
          key: circlecigen-tfvars-{{ .Revision }}-<< parameters.release-pipeline-name >>
          paths:
            - environments/
      - continuation/continue:
          configuration_path: .circleci/generated_config.yml

  integration-tests:
    description: Recurring job to run pipeline integration tests and detect aws configuration drift
    docker:
      - image: *executor-image
    parameters:
      instance_name:
        description: the VPC instance (and tfcloud workspace name) to run tests against
        type: string
      env-credentials:
        description: identifier for op.*.env file
        type: string
    steps:
      - checkout
      - set-environment:
          instance_name: << parameters.instance_name >>
          env-credentials: << parameters.env-credentials >>
      - run-inspec-tests:
          instance-name: << parameters.instance_name >>

workflows:
  version: 2

  development build:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - terraform/static-analysis:
          name: static analysis of psk-aws-platform-vpc terraform
          context: *context
          executor-image: *executor-image
          snyk-scan: false
          shell: op run --env-file op.nonprod.env -- /bin/bash -eo pipefail
          checkov-additional-args: --skip-check CKV_CIRCLECIPIPELINES_2
          before-static-analysis:
            - set-environment:
                static: true
                env-credentials: nonprod
          filters: *on-push-main

      - launch-dynamic-pipeline:
          name: generate sandbox pipeline
          context: *context
          release-pipeline-name: sandbox
          requires:
            - static analysis of psk-aws-platform-vpc terraform
          filters: *on-push-main

      - do/schedule-pipeline:
          name: Deploy sandbox nightly schedule
          context: *context
          executor-image-name: *executor-image
          shell: op run --env-file op.nonprod.env -- /bin/bash -eo pipefail
          scheduled-pipeline-name: Nightly VPC validation - sandbox
          scheduled-pipeline-description: |
            Automatically triggers nightly run of main pipeline for validating sandbox deployment pipeline vpcs
          hours-of-day: "[1]"
          days-of-week: "[\"SUN\"]"
          before-release:
            - set-environment:
                static: true
                env-credentials: nonprod
          filters: *on-push-main

      - do/schedule-pipeline:
          name: Deploy release nightly schedule
          context: *context
          executor-image-name: *executor-image
          shell: op run --env-file op.prod.env -- /bin/bash -eo pipefail
          scheduled-pipeline-name: Nightly VPC validation - release
          scheduled-pipeline-description: |
            Automatically triggers nightly run of main pipeline for validating vpcs in release
          hours-of-day: "[1]"
          days-of-week: "[\"SUN\"]"
          before-release:
            - set-environment:
                static: true
                env-credentials: prod
          filters: *on-push-main


  production release:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - launch-dynamic-pipeline:
          name: generate release pipeline
          context: *context
          release-pipeline-name: release
          filters: *on-tag-main


  run nightly sandbox validation jobs:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ nightly-sandbox-validation-schedule, << pipeline.schedule.name >> ]
    jobs:
      - launch-dynamic-pipeline:
          name: generate-sandbox-nightly-pipeline
          release-pipeline-name: sandbox
          custom-template-file: nightly.yml
          filters: *on-push-main

  run nightly release validation jobs:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ nightly-release-validation-schedule, << pipeline.schedule.name >> ]
    jobs:
      - launch-dynamic-pipeline:
          name: generate-platform-nightly-pipeline
          release-pipeline-name: release
          custom-template-file: nightly.yml
          filters: *on-push-main
