      - terraform/apply:
          name: apply {{instance_name}} change plan
          context: *context
          shell: op run --env-file op.{{env_credentials}}.env -- /bin/bash -eo pipefail
          workspace: {{instance_name}}
          before-terraform:
            - set-environment:
                instance-name: {{instance_name}}
                env-credentials: {{env_credentials}}
          after-terraform:
            - run-inspec-tests:
                instance-name: {{instance_name}}
          filters: {{filters}}
          requires:
            - approve {{role}} changes
