---
#apiVersion: karpenter.sh/v1beta1
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-amd-node-pool
  namespace: karpenter
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t","m","c"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t2","t3","m4","m5","m6i","m7i","c4","c5","c6i","c7i"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["xlarge","2xlarge","4xlarge"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: default-node-class
  limits:
    cpu: 80    # equal to approx a max of 5 of the largest allowable instance types
    ram: 320Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 336h # refresh all nodes 14days * 24h = 336h
