---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-arm-node-pool
  namespace: karpenter
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-node-class
      expireAfter: 336h # refresh all nodes 14days * 24h = 336h
      terminationGracePeriod: 24h
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m","c","r"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t4g","m6g","m7g","c6g","c6gn","c7g","c7gn","r6g","r7g"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["xlarge","2xlarge","4xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    # budgets:
    #   - nodes: 50%
    #   - schedule: "0 9 * * mon-fri"
    #     duration: 8h
    #     nodes: "0"
  limits:
    cpu: "80"
    memory: 320Gi
