---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-amd-node-pool
  namespace: karpenter
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-node-class
      expireAfter: 336h # refresh all nodes 14days * 24h = 336h
      terminationGracePeriod: 24h
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t","m","c"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t2","t3","m4","m5","m6i","m7i","c4","c5","c6i","c7i"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["xlarge","2xlarge","4xlarge"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    # budgets:
    #   - nodes: 50%
    #   - schedule: "0 9 * * mon-fri"
    #     duration: 8h
    #     nodes: "0"
  limits:
    cpu: "80"
    memory: 320Gi
