---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default-arm-node-pool
  namespace: karpenter
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m","c","r"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t4g","m6g","m7g","c6g","c6gn","c7g","c7gn","r6g","r7g"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["xlarge","2xlarge","4xlarge"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default-node-class
  limits:
    cpu: 80    # equal to approx a max of 5 of the largest allowable instance types
    ram: 320Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 336h # refresh all nodes 14days * 24h = 336h
