# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: development build

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

permissions:
  contents: read
  security-events: write

jobs:

  static-code-analysis:
    name: static code analysis
    uses: ThoughtWorks-DPS/terraform-action/.github/workflows/new.yaml@main
    with:
      cosign-version: 2.2.4
      terraform-version: 1.8.2
      tflint-version: 0.51.0
      checkov-version: 3.2.71
      snyk-version: 1.1291.0
      terrascan-version: 1.19.1
      trivy-version: 0.51.1